options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/stately-lambda-463716-s3/robrion-n8n:${SHORT_SHA}'
      - '.'
    
  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/stately-lambda-463716-s3/robrion-n8n:${SHORT_SHA}'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'robrion-n8n'
      - '--image=gcr.io/stately-lambda-463716-s3/robrion-n8n:${SHORT_SHA}'
      - '--region=us-central1'
      - '--platform=managed'
      - '--execution-environment=gen2'
      - '--memory=1Gi'
      - '--cpu=2'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--port=8080'
      - '--timeout=900'
      - '--set-env-vars=N8N_DB_SQLITE_FILE=/mnt/data/database.sqlite,N8N_PROTOCOL=https,N8N_LOG_LEVEL=info,N8N_METRICS=true,ROBRION_VERSION=1.0.0,ROBRION_ENVIRONMENT=production'
      - '--add-volume=name=robrion-n8n-volume,type=cloud-storage,bucket=robrion-n8n-storage'
      - '--add-volume-mount=volume=robrion-n8n-volume,mount-path=/mnt/data'
      - '--allow-unauthenticated'
      - '--service-account=robprian@stately-lambda-463716-s3.iam.gserviceaccount.com'

images:
  - 'gcr.io/stately-lambda-463716-s3/robrion-n8n:${SHORT_SHA}'